---

Lint/EmptyFile:
  Exclude:
    - 'spec/rails-2-test/config.ru'
    - 'spec/rails-3-test/config.ru'
    - 'spec/rails-4-test/config.ru'

# Rubocop Thinks Pathnames Are Strings
Style/StringConcatenation:
  Enabled:            false
