---

name:                             "Build"

on:
  - "push"
  - "pull_request"

jobs:
  test:
    name:                         "Testing"
    runs-on:                      "ubuntu-latest"

    strategy:
      matrix:
        ruby:
          - "2.7"
          - "3.0"
          - "3.1"
          - "3.2"
          - "3.3"
          - "3.4"
          - "ruby-head"

    continue-on-error:            ${{ endsWith(matrix.ruby, 'head') }}

    steps:
      - name:                     "Checkout Code"
        uses:                     "actions/checkout@v3"
        timeout-minutes:          5
        with:
          fetch-depth:            0

      - name:                     "Build Ruby"
        uses:                     "ruby/setup-ruby@v1"
        with:
          ruby-version:           "${{ matrix.ruby }}"
          bundler:                "2"
          bundler-cache:          true

      - name:                     "Run RSpec"
        run:                      |
          bundle exec rspec
